apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kub-volume

spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
      tier: apibackend
  template:
    metadata:
      labels: 
        app: story
        tier: apibackend
    spec:
      containers:
        - name: storynode
          image: robudex17/storyapi:v1
          volumeMounts:
            - name: story-volume
              mountPath: /app/story
      volumes:
         #This volume is reside on pods when the pods destroyed this volume also will destoryed
        # - name: story-volume
        #   emptyDir: {}
        - name: story-volume
          hostPath: 
            path: /data
            type: DirectoryOrCreate
      


          

