apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-data
  volumeMode: Filesystem
  resources:
    requests: 
      storage: 2Gi
  