apiVersion: v1
kind: Service

metadata:
  name: backendapi

spec:
  selector:
    app: story
    tier: apibackend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer     
