apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: 
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 8081
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer

  ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rogapp
      tier: backend
  template:
    metadata: 
      labels:
        app: rogapp
        tier: backend
    spec: 
      containers:
        - name: nodeapp
          image: robudex17/rognodeap:v3
        # - name: ...
        #   image: ...

