apiVersion: v1
kind: PersistentVolume
metadata: 
  name: host-pv 
spec:
  capacity:
    storage: 2Gi
    volumeMode: Filesystem
    storeClassName: standard 
    accessModes: 
      - ReadWriteOnce
    hostPath:
      path: /data 
      type: DirectoryOrCreate  