apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template: 
    metadata: 
      labels:
        app: users
    spec:
      containers: 
        - name: users
          image: robudex17/users_api:latest
          env:
            - name: AUTH_ADDRESS
              # this value is the dns of auth-service support by kubernetes
              value: auth-service.default 
      

  