version: "3.8"
services:
  mariadb:
    image: mariadb
    env_file:
      - ./env/db.env
    volumes:
      - ./database:/var/lib/mysql
    pro
  dbadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    env_file:
      - ./env/admin.env