version: "3.8"
services:
  mariadb:
    image: mariadb
    env_file:
      - ./env/db.env
    volumes:
      - sbtphdb:/var/lib/mysql
    ports:
      - 3307:3306
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8081:80
    env_file:
      - ./env/api.env

  dbadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    env_file:
      - ./env/admin.env
volumes:
  sbtphdb: