version: "3.8"
services:
  mariadb:
    image: mariadb
    env_file:
      - ./env/db.env
    volumes:
      - sbtphdb:/var/lib/mysql
    ports:
      - 3307:3306
  dbadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    env_file:
      - ./env/admin.env
ports:
  sbtphdb: