version: "3.8"
services:
  webserver:
     image: nginx:stable-alpine
     ports:
       - 8080:80
     volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - ./src:/var/www/html
     depends_on:
       - php
       - mysqldb
       
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html

  mysqldb:
    image: mysql
    volumes:
      - data:/var/lib/mysql
    env_file: ./env/mysql.env

  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # npm:
  # artisan:

# volumes:
#   - data: