job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github- edit by rogmer")
    scm {
        git("https://github.com/robudexIT/DEVOPS-JOURNEY.git", 'main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'jenkins/Jenkins_Upgradev3/maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
